---
- name: Install karabiner-elements
  community.general.homebrew_cask:
    name: karabiner-elements
    state: present
    install_options: debug,appdir=/Applications
  tags:
    - desktop

- name: Install more desktop apps
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: debug,appdir=/Applications
  loop: "{{ desktop_apps }}"
  tags:
    - desktop
