---
- name: Install tmux
  community.general.homebrew:
    name: tmux
    state: present
  tags:
    - tmux

#  https://github.com/gpakosz/.tmux.git
- name: Installing oh-my-tmux
  ansible.builtin.git:
    repo: https://github.com/gpakosz/.tmux.git
    dest: "{{ ansible_env.HOME }}/.tmux"
    update: true
    version: master
  tags:
    - tmux

- name: Create a symbolic link to .tmux.conf
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.tmux/.tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    state: link
    force: true
  tags:
    - tmux

- name: Create a symbolic link to .tmux.conf.local
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/dotfiles/.tmux.conf.local"
    dest: "{{ ansible_env.HOME }}/.tmux.conf.local"
    state: link
    force: true
  tags:
    - tmux
