---

# Node and packages

  # for global npm install without sudo
- name: Configure global npm install without sudo
  command: chown -hR {{user_name}}:{{ user_name }} /usr/local/
  when: is_ubuntu

- name: Update npm
  command: npm update -g npm

- name: Install global node modules
  npm: name={{ item }} global=yes
  with_items:
    - httpster
    - n
    - nodemon
    - browser-sync
    - localtunnel

- name: Update node
  command: n latest
  sudo: no
