---
- name: Before Mac OS defaults setup
  ansible.builtin.script: before_setup.sh
  become: true

- name: Mac OS system defaults setup
  ansible.builtin.script: "{{ item }}"
  with_items:
    - system/general.sh
    - system/screen.sh
    - system/energy_saving.sh
    - system/input_devices.sh
    - system/disk_utility_and_other.sh
    - system/dock_dashboard_hot_corners.sh
    - system/finder.sh
    - system/mac_app_store.sh
    - system/activity_monitor.sh
    - system/messages.sh
    - system/photos.sh
    - system/safari.sh
    - system/spotlight.sh
    - system/time_machine.sh

- name: Mac OS apps defaults setup
  ansible.builtin.script: "{{ item }}"
  with_items:
    - apps/chrome.sh
    - apps/moom.sh
    - apps/opera.sh
    - apps/terminal_and_iterm2.sh
    - apps/webstorm.sh

- name: After Mac OS defaults setup
  ansible.builtin.script: after_setup.sh
  become: true

# - name: Setup Dock
#   script: setup_macos_dock.sh
