---
# SEE more cli apps https://github.com/agarrharr/awesome-cli-apps#macos

# - name: Check git dotfiles
#  stat:
#    path: "{{ ansible_env.HOME }}/{{ item }}"
#  register: results
#  with_items:
#    - .gitconfig
#    - .gitignore_global

# - debug:
#    var: results
# - name: Remove old .gitconfig and .gitignore_global if exists
#  file:
#    path: "{{ ansible_env.HOME }}/{{ item }}"
#    state: absent
#  with_items:
#    - .gitconfig
#    - .gitignore_global

# TODO:
# install "nvm" https://github.com/nvm-sh/nvm#nvmrc
- name: Install vagrant
  community.general.homebrew:
    name: vagrant
    state: present
  ignore_errors: true

- name: Install more cli apps
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  ignore_errors: true
  loop: "{{ cli_apps }}"

# setup docker-compose as a plugin
- name: Ensures "~/.docker/cli-plugins" dir exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.docker/cli-plugins"
    state: directory

- name: Symlinc docker-compose as a docker plugin
  ansible.builtin.file:
    src: /usr/local/opt/docker-compose/bin/docker-compose
    dest: "{{ ansible_env.HOME }}/.docker/cli-plugins/docker-compose"
    state: link
    force: true

- name: Install node based packages
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: present
  ignore_errors: true
  loop: "{{ node_packages }}"
