---

#- name: Check git dotfiles
#  stat:
#    path: "{{ ansible_env.HOME }}/{{ item }}"
#  register: results
#  with_items:
#    - .gitconfig
#    - .gitignore_global

#- debug:
#    var: results
#- name: Remove old .gitconfig and .gitignore_global if exists
#  file:
#    path: "{{ ansible_env.HOME }}/{{ item }}"
#    state: absent
#  with_items:
#    - .gitconfig
#    - .gitignore_global

- name: Install karabiner-elements
  homebrew_cask:
    name: karabiner-elements
    state: present
    install_options: 'debug,appdir=/Applications'

- name: Install vagrant
  homebrew:
    name:  vagrant
    state: present
  ignore_errors: True

- name: Install more cli apps
  homebrew:
    name: "{{ item }}"
    state: present
  ignore_errors: True
  loop:
    - git
    - jq
    - htop
    - git-lfs
    - hub
    - nginx
    - node
    - editorconfig
    - openconnect
    - openssl
    - openvpn
    - readline
    - python
    - watchman
    - pnpm
    - wget
    - the_silver_searcher
    - ipcalc
    - reattach-to-user-namespace
    - colima
    - redis
    - sqlite
    - dockutil
    - python3
    - podman
    - docker
    - docker-compose
    - docker-buildx
    - vagrant-completion
    - minikube
    - tree
    - mkcert
    - hey
    - wrk
#    - npkill # not available in brew
#    - relabel # not available in brew
#    - delta # not available in brew
    - tig


# setup docker-compose as a plugin
- name: Ensures "~/.docker/cli-plugins" dir exists
  file:
    path: "{{ ansible_env.HOME }}/.docker/cli-plugins"
    state: directory
     
- name: Symlinc docker-compose as a docker plugin
  file:
    src: "/usr/local/opt/docker-compose/bin/docker-compose"
    dest: "{{ ansible_env.HOME }}/.docker/cli-plugins/docker-compose"
    state: link
    force: yes

