---
# SEE more cli apps https://github.com/agarrharr/awesome-cli-apps#macos

# - name: Check git dotfiles
#  stat:
#    path: "{{ ansible_env.HOME }}/{{ item }}"
#  register: results
#  with_items:
#    - .gitconfig
#    - .gitignore_global

# - debug:
#    var: results
# - name: Remove old .gitconfig and .gitignore_global if exists
#  file:
#    path: "{{ ansible_env.HOME }}/{{ item }}"
#    state: absent
#  with_items:
#    - .gitconfig
#    - .gitignore_global

# depricated
#- name: Tap a Homebrew "homebrew/cask-fonts"
#  community.general.homebrew_tap:
#    name: homebrew/cask-fonts
#    state: present
#  tags:
#    - homebrew

- name: Vagrant Block
  block:
    - name: Vagrant exists
      stat:
        path: /usr/local/bin/vagrant
      register: vagrant_exists

    - name: Debug vagrant_exists
      debug:
        var: vagrant_exists

    - name: Install vagrant
      community.general.homebrew:
        name: vagrant
        state: present
      ignore_errors: true
      when: vagrant_exists.stat.exists == false
  tags:
    - vagrant
    - homebrew

- name: Install more cli apps
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  ignore_errors: true
  loop: "{{ cli_apps }}"
  tags:
    - homebrew

# setup docker-compose as a plugin
- name: Ensures "~/.docker/cli-plugins" dir exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.docker/cli-plugins"
    state: directory
  tags:
    - homebrew

- name: Symlink docker-compose as a docker plugin
  ansible.builtin.file:
    src: /usr/local/opt/docker-compose/bin/docker-compose
    dest: "{{ ansible_env.HOME }}/.docker/cli-plugins/docker-compose"
    state: link
    force: true
  tags:
    - homebrew

- name: Install node based packages
  community.general.pnpm:
    name: "{{ item }}"
    global: true
    state: present
  ignore_errors: true
  loop: "{{ node_packages }}"
  tags:
    - pnpm
