---

#- name: Check git dotfiles
#  stat:
#    path: "{{ ansible_env.HOME }}/{{ item }}"
#  register: results
#  with_items:
#    - .gitconfig
#    - .gitignore_global

#- debug:
#    var: results
#- name: Remove old .gitconfig and .gitignore_global if exists
#  file:
#    path: "{{ ansible_env.HOME }}/{{ item }}"
#    state: absent
#  with_items:
#    - .gitconfig
#    - .gitignore_global

- name: Create a symbolic links for git
  file:
    src: "{{ ansible_env.HOME }}/dotfiles/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
    force: true
  with_items:
    - .gitconfig
    - .gitignore_global

- name: Install karabiner-elements
  homebrew_cask:
    name: karabiner-elements
    state: present
    install_options: 'debug,appdir=/Applications'

- name: Ensures "~/.config" dir exists
  file: 
    path: "{{ ansible_env.HOME }}/.config"
    state: directory    

- name: Remove karabiner default config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/karabiner"
    state: absent

- name: Create a symbolic link to config in ~/dotfiles/karabiner
  file:
    src: "{{ ansible_env.HOME }}/dotfiles/karabiner"
    dest: "{{ ansible_env.HOME }}/.config/karabiner"
    state: link
    force: yes

- name: Install iterm2
  homebrew_cask:
    name: iterm2
    state: present
    install_options: 'debug,appdir=/Applications'

- name: Create iterm2 config directory
  file:
    path: "{{ ansible_env.HOME }}/Library/Application Support/iTerm2"
    state: directory
    force: yes

- name: Create a symbolic link to iterm2 DynamicProfiles directory
  file:
    src: "{{ ansible_env.HOME }}/dotfiles/DynamicProfiles"
    dest: "{{ ansible_env.HOME }}/Library/Application Support/iTerm2/DynamicProfiles"
    state: link
    force: yes

- name: Install more cli apps
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - jq
    - htop
    - git-lfs
    - hub
    - nginx
    - node
    - editorconfig
    - openconnect
    - openssl
    - openvpn
    - readline
    - python
    - watchman
    - yarn
    - wget
    - the_silver_searcher
    - ipcalc
    - reattach-to-user-namespace
    - redis
    - sqlite
    - dockutil
    - python3

- name: Install more desktop apps
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: 'debug,appdir=/Applications'
  loop:
    - webstorm
    - sublime-text
    - alfred
    - skype
    - dropbox
    - private-internet-access
    - sourcetree
    - tunnelblick
    - zeplin
    - docker
    - anki
#   - firefox-developer-edition
    - teamviewer
    - 4k-video-downloader
    - vlc
    - vagrant
    - ichm
    - igetter
    # - dictionaries
    - zoomus
#    - istat-menus